In [3]:
import tensorflow as tf

x1 = tf.constant(1, dtype=tf.float32)
y1 = tf.constant(2, dtype=tf.float32)
point1 = tf.pack([x1, y1])


In [10]:
with tf.Session() as session:
    print(session.run(point1))
    print(session.run(tf.transpose([point1])))

[ 1.  2.]
[[ 1.]
 [ 2.]]


In [13]:
x2 = tf.constant(2, dtype=tf.float32)
y2 = tf.constant(3, dtype=tf.float32)
point2 = tf.pack([x2, y2])

with tf.Session() as session:
    print(session.run(point1))    
    print(session.run(point2))

[ 1.  2.]
[ 2.  3.]


In [14]:
points = tf.transpose(tf.pack([point1, point2]))

In [15]:
with tf.Session() as session:
    print(session.run(points))

[[ 1.  2.]
 [ 2.  3.]]


In [24]:
ones = tf.ones((1, 2))

params = tf.matmul(ones, tf.matrix_inverse(points))

with tf.Session() as session:
    result = session.run(params)
    print(result)

    
    print(session.run(ones))
    print(session.run(tf.matrix_inverse(points)))
    #print(session.run(tf.matrix_determinant(points)))

[[-1.  1.]]
[[ 1.  1.]]
[[-3.  2.]
 [ 2. -1.]]


In [34]:
# Canonical equation for the circle: x^2 + y^2 + dx + ey + f = 0
points = tf.constant([[2, 1],
                      [0, 5],
                      [-1, 2]], dtype=tf.float64)

A = tf.constant([
    [2, 1, 1],
    [0, 5, 1],
    [-1, 2, 1]
], dtype='float64')

B = -tf.constant([[5], [25], [5]])
X = tf.matrix_solve(A, B)
with tf.Session() as session:
    result = session.run(X)
    D, E, F = result.flatten()

    print(D, E, F)


TypeError: Input 'rhs' of 'MatrixSolve' Op has type int32 that does not match type float64 of argument 'matrix'.

In [31]:
B = -tf.constant([[5], [25], [5]])
with tf.Session() as session:
    print(session.run(B))

[[ -5]
 [-25]
 [ -5]]
